DROP TABLE IF EXISTS public.employee_data;
CREATE TABLE public.employee_data (
    id SERIAL PRIMARY KEY,
    user_id TEXT UNIQUE,
    password TEXT,
    "PersonID" TEXT,
    "PersonnelNumber" TEXT,
    "SCGEmployeeID" TEXT,
    "NamePrefixThai" TEXT,
    "FirstNameThai" TEXT,
    "LastNameThai" TEXT,
    "NamePrefixEnglish" TEXT,
    "FirstNameEnglish" TEXT,
    "LastNameEnglish" TEXT,
    "NickName" TEXT,
    "PositionID" TEXT,
    "PositionNameThai" TEXT,
    "PrimaryPosition" TEXT,
    "PLGroup" TEXT,
    "OrganizationID" TEXT,
    "Sub1ShiftThai" TEXT,
    "ShiftThai" TEXT,
    "Sub1SectionThai" TEXT,
    "SectionThai" TEXT,
    "Sub1DepartmentThai" TEXT,
    "DepartmentThai" TEXT,
    "Sub1DivisionThai" TEXT,
    "DivisionThai" TEXT,
    "Sub1CompanyThai" TEXT,
    "CompanyThai" TEXT,
    "Sub11BusinessUnitThai" TEXT,
    "Sub1BusinessUnitThai" TEXT,
    "BusinessUnitDescriptionThai" TEXT,
    "PositionEnglish" TEXT,
    "Sub1ShiftEnglish" TEXT,
    "ShiftEnglish" TEXT,
    "Sub1SectionEnglish" TEXT,
    "SectionEnglish" TEXT,
    "Sub1DepartmentEnglish" TEXT,
    "DepartmentEnglish" TEXT,
    "Sub1DivisionEnglish" TEXT,
    "DivisionEnglish" TEXT,
    "Sub1CompanyEnglish" TEXT,
    "CompanyEnglish" TEXT,
    "CompanyCode" TEXT,
    "Sub11BusinessUnitEnglish" TEXT,
    "Sub1BusinessUnitEnglish" TEXT,
    "BusinessUnitDescriptionEnglish" TEXT,
    "BusinessUnitCode" TEXT,
    "OrganizationIndexForSorting" TEXT,
    "ConsolidateCompany" TEXT,
    "HeadOfOrganizationUnit" TEXT,
    "ApproverLevelCode" TEXT,
    "ApproverLevel" TEXT,
    "PositionStructureLevelCode" TEXT,
    "PositionStructureLevel" TEXT,
    "OrgStructureLevelCode" TEXT,
    "OrgStructureLevel" TEXT,
    "MSSSAPAuthorization" TEXT,
    "HRSAPAuthorization" TEXT,
    "PersonnelAreaCode" TEXT,
    "PersonnelArea" TEXT,
    "PersonnelSubAreaCode" TEXT,
    "PersonnelSubArea" TEXT,
    "WorkingLocationCode" TEXT,
    "WorkingLocation" TEXT,
    "EmploymentStatusText" TEXT,
    "CostCenterPayment" TEXT,
    "CostCenterOrganization" TEXT,
    "WorkContract" TEXT,
    "PayrollArea" TEXT,
    "OrgKey" TEXT,
    "ReportToPersonnelNumber" TEXT,
    "ReportToName" TEXT,
    "ReportToPosition" TEXT,
    "ReportToPositionName" TEXT,
    "ReportToEmail" TEXT,
    "ManagerPersonnelNumber" TEXT,
    "ManagerName" TEXT,
    "ManagerPosition" TEXT,
    "ManagerPositionName" TEXT,
    "ManagerEmail" TEXT,
    "TelephoneHome" TEXT,
    "TelephoneMobile" TEXT,
    "OfficeAddress" TEXT,
    "USER" TEXT,
    "EmailAddressBusiness" TEXT,
    "TelephoneBusiness" TEXT,
    "TelephoneBeside" TEXT,
    "KeyDate" TEXT,
    "SystemDate" TEXT,
    "DOALevelCode" TEXT,
    "DOALevelText" TEXT,
    "RecordDate" TEXT,
    "Pipeline" TEXT,
    "FullName" TEXT
);

INSERT INTO public.employee_data (user_id, password, "PersonID", "PersonnelNumber", "SCGEmployeeID", "NamePrefixThai", "FirstNameThai", "LastNameThai", "NamePrefixEnglish", "FirstNameEnglish", "LastNameEnglish", "NickName", "PositionID", "PositionNameThai", "PrimaryPosition", "PLGroup", "OrganizationID", "Sub1ShiftThai", "ShiftThai", "Sub1SectionThai", "SectionThai", "Sub1DepartmentThai", "DepartmentThai", "Sub1DivisionThai", "DivisionThai", "Sub1CompanyThai", "CompanyThai", "Sub11BusinessUnitThai", "Sub1BusinessUnitThai", "BusinessUnitDescriptionThai", "PositionEnglish", "Sub1ShiftEnglish", "ShiftEnglish", "Sub1SectionEnglish", "SectionEnglish", "Sub1DepartmentEnglish", "DepartmentEnglish", "Sub1DivisionEnglish", "DivisionEnglish", "Sub1CompanyEnglish", "CompanyEnglish", "CompanyCode", "Sub11BusinessUnitEnglish", "Sub1BusinessUnitEnglish", "BusinessUnitDescriptionEnglish", "BusinessUnitCode", "OrganizationIndexForSorting", "ConsolidateCompany", "HeadOfOrganizationUnit", "ApproverLevelCode", "ApproverLevel", "PositionStructureLevelCode", "PositionStructureLevel", "OrgStructureLevelCode", "OrgStructureLevel", "MSSSAPAuthorization", "HRSAPAuthorization", "PersonnelAreaCode", "PersonnelArea", "PersonnelSubAreaCode", "PersonnelSubArea", "WorkingLocationCode", "WorkingLocation", "EmploymentStatusText", "CostCenterPayment", "CostCenterOrganization", "WorkContract", "PayrollArea", "OrgKey", "ReportToPersonnelNumber", "ReportToName", "ReportToPosition", "ReportToPositionName", "ReportToEmail", "ManagerPersonnelNumber", "ManagerName", "ManagerPosition", "ManagerPositionName", "ManagerEmail", "TelephoneHome", "TelephoneMobile", "OfficeAddress", "USER", "EmailAddressBusiness", "TelephoneBusiness", "TelephoneBeside", "KeyDate", "SystemDate", "DOALevelCode", "DOALevelText", "RecordDate", "Pipeline", "FullName") VALUES 
('thidas', 'Pass@1234', 324453, 2243234, 2234322, 'นาง', 'ทาทา', 'น้อยไหม', 'Mrs.', 'Tata', 'Noi', 'เอ', 90021515, 'ธุรการ', 'Y', 'M', 90000009, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'บริษัท เอสซีจี ซิเมนต์-ผลิตภัณฑ์ก่อสร้าง จำกัด', NULL, NULL, 'SCG Smart Living Business', 'Senior Secretary', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'SCG Cement-Building Materials Co.,Ltd.', 180, NULL, NULL, 'SCG Smart Living Business', 'SL', 11088, 'CONSOLIDATED', 'N', NULL, NULL, NULL, NULL, 10, 'Business Unit', 'N', 'N', 'T014', 'SCG CBM - Bangsue', 'TH04', 'Bangkok', '018T0U', 'CBM DM - Bangsue @13.805857,100.538002', 'Active', '0380-30000', '0380-30000', 'OFFICE', 'YD', 'CBM-YD-0180C-_', 90004281, 'Mr. Wiroat', 72484, 'President, SCG Smart Living Business', 'VIROJR@SCG.COM', 90004281, 'Mr. Wiroat Rattanachaisit', 72484, 'President, SCG Smart Living Business', 'VIROJR@SCG.COM', 22666677, 832456543, 'สำนักงานใหญ่ 1 ชั้น 3 ชั้น 3', 'THIDAS', 'THA@CCR.COM', 25862164, 25862164, '2026-06-19 00:00:00', '2026-06-19 00:00:00', NULL, NULL, '2026-06-18 19:15:22', 'gcrf-gcs-bigquery-orchestrator', 'ทาทา น้อยไหม'),
('admin', 'Admin', NULL, NULL, NULL, 'คุณ', 'admin', '(Admin)', NULL, NULL, NULL, NULL, NULL, 'Admin', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'admin@company.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'admin (Admin)'),
('somchai.j', 'Pass@1234', NULL, NULL, NULL, 'คุณ', 'somchai.j', '(Admin)', NULL, NULL, NULL, NULL, NULL, 'หัวหน้างานซ่อม', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'somchai.j@company.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'somchai.j (Admin)'),
('somsri.m', 'Pass@1234', NULL, NULL, NULL, 'คุณ', 'somsri.m', '(Admin)', NULL, NULL, NULL, NULL, NULL, 'หัวหน้าหมวดซ่อม', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'somsri.m@company.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'somsri.m (Admin)'),
('ratthasart.m', 'Pass@1234', NULL, NULL, NULL, 'คุณ', 'ratthasart.m', '(Admin)', NULL, NULL, NULL, NULL, NULL, 'เจ้าหน้าที่บัญชี', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ratthasart.m@company.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ratthasart.m (Admin)'),
('wichai.r', 'Pass@1234', NULL, NULL, NULL, 'คุณ', 'wichai.r', '(Admin)', NULL, NULL, NULL, NULL, NULL, 'HR BP Manager', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'wichai.r@company.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'wichai.r (Admin)'),
('mana.c', 'Pass@1234', NULL, NULL, NULL, 'คุณ', 'mana.c', '(Admin)', NULL, NULL, NULL, NULL, NULL, 'ช่างซ่อมไฟฟ้า', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'mana.c@company.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'mana.c (Admin)'),
('piti.s', 'Pass@1234', NULL, NULL, NULL, 'คุณ', 'piti.s', '(Admin)', NULL, NULL, NULL, NULL, NULL, 'ผู้จัดการโรงงาน', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'piti.s@company.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'piti.s (Admin)'),
('choojai.b', 'Pass@1234', NULL, NULL, NULL, 'คุณ', 'choojai.b', '(Admin)', NULL, NULL, NULL, NULL, NULL, 'HR BP Officer', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'choojai.b@company.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'choojai.b (Admin)'),
('weera.n', 'Pass@1234', NULL, NULL, NULL, 'คุณ', 'weera.n', '(Admin)', NULL, NULL, NULL, NULL, NULL, 'HR BP Officer', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'weera.n@company.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'weera.n (Admin)'),
('arun.p', 'Pass@1234', NULL, NULL, NULL, 'คุณ', 'arun.p', '(Admin)', NULL, NULL, NULL, NULL, NULL, 'พนักงานขาย', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'arun.p@company.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'arun.p (Admin)');

-- Insert 30 simulated employees
INSERT INTO public.employee_data (
    "user_id", "password", "FullName", "FirstNameThai", "LastNameThai", "PositionNameThai", "SectionThai", "DepartmentThai", "Sub1DivisionThai", "DivisionThai", "Sub1CompanyThai", "CompanyThai", "PersonnelArea", "ReportToName", "ReportToEmail", "EmailAddressBusiness"
) VALUES
    ('usr001', 'Password123', 'สมปอง ใจดี', 'สมปอง', 'ใจดี', 'พนักงานควบคุมเครื่องจักร', 'หน่วยซ่อมไฟฟ้า', 'ฝ่ายซ่อมบำรุง', 'ส่วนงานวิศวกรรมโรงงาน', 'โรงงานสระบุรี', 'ธุรกิจบรรจุภัณฑ์', 'บริษัท เอสซีจี รูฟฟิ่ง จำกัด', 'Saraburi', 'อารีย์ ไดเรกเตอร์', 'mgr_1@company.com', 'user1@company.com'),
    ('usr002', 'Password123', 'วิชัย รักไทย', 'วิชัย', 'รักไทย', 'พนักงานคลังสินค้า', 'หน่วยซ่อมเครื่องกล', 'ฝ่ายซัพพลายเชน', 'ส่วนงานวิศวกรรมโรงงาน', 'โรงงานสระบุรี', 'ธุรกิจบรรจุภัณฑ์', 'บริษัท เอสซีจี แพคเกจจิ้ง จำกัด (มหาชน)', 'Saraburi', 'สมชาย หัวหน้างาน', 'mgr_3@company.com', 'user2@company.com'),
    ('usr003', 'Password123', 'กิตติ คงมั่น', 'กิตติ', 'คงมั่น', 'เจ้าหน้าที่ความปลอดภัย', 'หน่วยคลังสินค้า', 'ฝ่ายผลิต', 'ส่วนงานสนับสนุน', 'โรงงานสระบุรี', 'ธุรกิจผลิตภัณฑ์ก่อสร้าง', 'บริษัท เอสซีจี ซิเมนต์ จำกัด', 'Rayong', 'วิชัย ผู้จัดการ', 'mgr_1@company.com', 'user3@company.com'),
    ('usr004', 'Password123', 'มานะ สว่างวงศ์', 'มานะ', 'สว่างวงศ์', 'วิศวกรไฟฟ้า', 'หน่วยซ่อมไฟฟ้า', 'ฝ่ายซัพพลายเชน', 'ส่วนงานสนับสนุน', 'โรงงานระยอง', 'ธุรกิจผลิตภัณฑ์ก่อสร้าง', 'บริษัท เอสซีจี แพคเกจจิ้ง จำกัด (มหาชน)', 'Saraburi', 'สมชาย หัวหน้างาน', 'mgr_5@company.com', 'user4@company.com'),
    ('usr005', 'Password123', 'ปรีชา เจริญพร', 'ปรีชา', 'เจริญพร', 'พนักงานควบคุมเครื่องจักร', 'หน่วยผลิต 2', 'ฝ่ายซ่อมบำรุง', 'ส่วนงานสนับสนุน', 'โรงงานสระบุรี', 'ธุรกิจผลิตภัณฑ์ก่อสร้าง', 'บริษัท เอสซีจี แพคเกจจิ้ง จำกัด (มหาชน)', 'Bangkok', 'สมชาย หัวหน้างาน', 'mgr_4@company.com', 'user5@company.com'),
    ('usr006', 'Password123', 'สมชาย มีทรัพย์', 'สมชาย', 'มีทรัพย์', 'ช่างซ่อมเครื่องกล', 'หน่วยความปลอดภัย', 'ฝ่ายความปลอดภัยและสิ่งแวดล้อม', 'ส่วนงานปฏิบัติการ', 'โรงงานบางซื่อ', 'ธุรกิจซิเมนต์', 'บริษัท เอสซีจี แพคเกจจิ้ง จำกัด (มหาชน)', 'Rayong', 'สมชาย หัวหน้างาน', 'mgr_3@company.com', 'user6@company.com'),
    ('usr007', 'Password123', 'ชาติชาย ยอดเยี่ยม', 'ชาติชาย', 'ยอดเยี่ยม', 'พนักงานธุรการ', 'หน่วยซ่อมไฟฟ้า', 'ฝ่ายซ่อมบำรุง', 'ส่วนงานวิศวกรรมโรงงาน', 'โรงงานระยอง', 'ธุรกิจผลิตภัณฑ์ก่อสร้าง', 'บริษัท เอสซีจี ซิเมนต์ จำกัด', 'Bangkok', 'กิตติ สุวรรณ', 'mgr_5@company.com', 'user7@company.com'),
    ('usr008', 'Password123', 'อารีย์ เก่งกาจ', 'อารีย์', 'เก่งกาจ', 'พนักงานธุรการ', 'หน่วยความปลอดภัย', 'ฝ่ายซัพพลายเชน', 'ส่วนงานปฏิบัติการ', 'โรงงานระยอง', 'ธุรกิจบรรจุภัณฑ์', 'บริษัท เอสซีจี รูฟฟิ่ง จำกัด', 'Rayong', 'กิตติ สุวรรณ', 'mgr_3@company.com', 'user8@company.com'),
    ('usr009', 'Password123', 'ยุพา มั่นคง', 'ยุพา', 'มั่นคง', 'หัวหน้ากะ', 'หน่วยผลิต 1', 'ฝ่ายซ่อมบำรุง', 'ส่วนงานวิศวกรรมโรงงาน', 'โรงงานระยอง', 'ธุรกิจบรรจุภัณฑ์', 'บริษัท เอสซีจี แพคเกจจิ้ง จำกัด (มหาชน)', 'Bangkok', 'วิชัย ผู้จัดการ', 'mgr_2@company.com', 'user9@company.com'),
    ('usr010', 'Password123', 'วันทนา บุญส่ง', 'วันทนา', 'บุญส่ง', 'เจ้าหน้าที่ความปลอดภัย', 'หน่วยผลิต 1', 'ฝ่ายซ่อมบำรุง', 'ส่วนงานสนับสนุน', 'โรงงานระยอง', 'ธุรกิจซิเมนต์', 'บริษัท เอสซีจี ซิเมนต์ จำกัด', 'Saraburi', 'วิชัย ผู้จัดการ', 'mgr_2@company.com', 'user10@company.com'),
    ('usr011', 'Password123', 'สมศรี ทองดี', 'สมศรี', 'ทองดี', 'เจ้าหน้าที่ความปลอดภัย', 'หน่วยผลิต 1', 'ฝ่ายความปลอดภัยและสิ่งแวดล้อม', 'ส่วนงานวิศวกรรมโรงงาน', 'โรงงานสระบุรี', 'ธุรกิจบรรจุภัณฑ์', 'บริษัท เอสซีจี แพคเกจจิ้ง จำกัด (มหาชน)', 'Rayong', 'ประยุทธ์ มั่นคง', 'mgr_1@company.com', 'user11@company.com'),
    ('usr012', 'Password123', 'ประยุทธ์ สุขสวัสดิ์', 'ประยุทธ์', 'สุขสวัสดิ์', 'พนักงานธุรการ', 'หน่วยความปลอดภัย', 'ฝ่ายความปลอดภัยและสิ่งแวดล้อม', 'ส่วนงานปฏิบัติการ', 'โรงงานบางซื่อ', 'ธุรกิจผลิตภัณฑ์ก่อสร้าง', 'บริษัท เอสซีจี ซิเมนต์ จำกัด', 'Bangkok', 'กิตติ สุวรรณ', 'mgr_1@company.com', 'user12@company.com'),
    ('usr013', 'Password123', 'สมศักดิ์ พิชัยญาณ', 'สมศักดิ์', 'พิชัยญาณ', 'ช่างซ่อมเครื่องกล', 'หน่วยซ่อมไฟฟ้า', 'ฝ่ายซัพพลายเชน', 'ส่วนงานปฏิบัติการ', 'โรงงานสระบุรี', 'ธุรกิจซิเมนต์', 'บริษัท เอสซีจี ซิเมนต์ จำกัด', 'Rayong', 'วิชัย ผู้จัดการ', 'mgr_5@company.com', 'user13@company.com'),
    ('usr014', 'Password123', 'นพดล วิเศษกุล', 'นพดล', 'วิเศษกุล', 'วิศวกรไฟฟ้า', 'หน่วยคลังสินค้า', 'ฝ่ายซ่อมบำรุง', 'ส่วนงานสนับสนุน', 'โรงงานสระบุรี', 'ธุรกิจผลิตภัณฑ์ก่อสร้าง', 'บริษัท เอสซีจี รูฟฟิ่ง จำกัด', 'Rayong', 'ประยุทธ์ มั่นคง', 'mgr_3@company.com', 'user14@company.com'),
    ('usr015', 'Password123', 'ณัฐพล รัตนพันธ์', 'ณัฐพล', 'รัตนพันธ์', 'วิศวกรเครื่องกล', 'หน่วยผลิต 2', 'ฝ่ายผลิต', 'ส่วนงานปฏิบัติการ', 'โรงงานสระบุรี', 'ธุรกิจบรรจุภัณฑ์', 'บริษัท เอสซีจี รูฟฟิ่ง จำกัด', 'Saraburi', 'กิตติ สุวรรณ', 'mgr_4@company.com', 'user15@company.com'),
    ('usr016', 'Password123', 'ธีรภัทร สิงห์ทอง', 'ธีรภัทร', 'สิงห์ทอง', 'ช่างซ่อมไฟฟ้า', 'หน่วยซ่อมไฟฟ้า', 'ฝ่ายผลิต', 'ส่วนงานปฏิบัติการ', 'โรงงานสระบุรี', 'ธุรกิจผลิตภัณฑ์ก่อสร้าง', 'บริษัท เอสซีจี ซิเมนต์ จำกัด', 'Rayong', 'สมชาย หัวหน้างาน', 'mgr_5@company.com', 'user16@company.com'),
    ('usr017', 'Password123', 'อนุชา วิริยะ', 'อนุชา', 'วิริยะ', 'พนักงานควบคุมเครื่องจักร', 'หน่วยซ่อมไฟฟ้า', 'ฝ่ายซัพพลายเชน', 'ส่วนงานสนับสนุน', 'โรงงานบางซื่อ', 'ธุรกิจซิเมนต์', 'บริษัท เอสซีจี แพคเกจจิ้ง จำกัด (มหาชน)', 'Bangkok', 'ประยุทธ์ มั่นคง', 'mgr_3@company.com', 'user17@company.com'),
    ('usr018', 'Password123', 'ศักดิ์ชัย ประเสริฐผล', 'ศักดิ์ชัย', 'ประเสริฐผล', 'พนักงานธุรการ', 'หน่วยซ่อมเครื่องกล', 'ฝ่ายซ่อมบำรุง', 'ส่วนงานปฏิบัติการ', 'โรงงานสระบุรี', 'ธุรกิจซิเมนต์', 'บริษัท เอสซีจี ซิเมนต์ จำกัด', 'Rayong', 'ประยุทธ์ มั่นคง', 'mgr_2@company.com', 'user18@company.com'),
    ('usr019', 'Password123', 'สุพจน์ จันทร์โอชา', 'สุพจน์', 'จันทร์โอชา', 'วิศวกรไฟฟ้า', 'หน่วยซ่อมไฟฟ้า', 'ฝ่ายซ่อมบำรุง', 'ส่วนงานสนับสนุน', 'โรงงานระยอง', 'ธุรกิจบรรจุภัณฑ์', 'บริษัท เอสซีจี แพคเกจจิ้ง จำกัด (มหาชน)', 'Saraburi', 'ประยุทธ์ มั่นคง', 'mgr_5@company.com', 'user19@company.com'),
    ('usr020', 'Password123', 'วสันต์ ทรัพย์สิน', 'วสันต์', 'ทรัพย์สิน', 'ช่างซ่อมเครื่องกล', 'หน่วยผลิต 2', 'ฝ่ายความปลอดภัยและสิ่งแวดล้อม', 'ส่วนงานวิศวกรรมโรงงาน', 'โรงงานบางซื่อ', 'ธุรกิจผลิตภัณฑ์ก่อสร้าง', 'บริษัท เอสซีจี รูฟฟิ่ง จำกัด', 'Bangkok', 'กิตติ สุวรรณ', 'mgr_1@company.com', 'user20@company.com'),
    ('usr021', 'Password123', 'วรวิทย์ เลิศหล้า', 'วรวิทย์', 'เลิศหล้า', 'ช่างซ่อมเครื่องกล', 'หน่วยซ่อมเครื่องกล', 'ฝ่ายความปลอดภัยและสิ่งแวดล้อม', 'ส่วนงานวิศวกรรมโรงงาน', 'โรงงานบางซื่อ', 'ธุรกิจผลิตภัณฑ์ก่อสร้าง', 'บริษัท เอสซีจี แพคเกจจิ้ง จำกัด (มหาชน)', 'Rayong', 'สมชาย หัวหน้างาน', 'mgr_3@company.com', 'user21@company.com'),
    ('usr022', 'Password123', 'ชลธร มงคลชัย', 'ชลธร', 'มงคลชัย', 'พนักงานธุรการ', 'หน่วยซ่อมเครื่องกล', 'ฝ่ายความปลอดภัยและสิ่งแวดล้อม', 'ส่วนงานปฏิบัติการ', 'โรงงานบางซื่อ', 'ธุรกิจผลิตภัณฑ์ก่อสร้าง', 'บริษัท เอสซีจี ซิเมนต์ จำกัด', 'Rayong', 'ประยุทธ์ มั่นคง', 'mgr_3@company.com', 'user22@company.com'),
    ('usr023', 'Password123', 'ทิพวรรณ พงษ์ศักดิ์', 'ทิพวรรณ', 'พงษ์ศักดิ์', 'วิศวกรซ่อมบำรุง', 'หน่วยซ่อมไฟฟ้า', 'ฝ่ายซ่อมบำรุง', 'ส่วนงานปฏิบัติการ', 'โรงงานบางซื่อ', 'ธุรกิจผลิตภัณฑ์ก่อสร้าง', 'บริษัท เอสซีจี รูฟฟิ่ง จำกัด', 'Saraburi', 'สมชาย หัวหน้างาน', 'mgr_2@company.com', 'user23@company.com'),
    ('usr024', 'Password123', 'รัตนา พิทักษ์', 'รัตนา', 'พิทักษ์', 'ช่างซ่อมเครื่องกล', 'หน่วยผลิต 2', 'ฝ่ายผลิต', 'ส่วนงานปฏิบัติการ', 'โรงงานสระบุรี', 'ธุรกิจซิเมนต์', 'บริษัท เอสซีจี แพคเกจจิ้ง จำกัด (มหาชน)', 'Rayong', 'สมชาย หัวหน้างาน', 'mgr_2@company.com', 'user24@company.com'),
    ('usr025', 'Password123', 'นฤมล ไพศาล', 'นฤมล', 'ไพศาล', 'พนักงานควบคุมเครื่องจักร', 'หน่วยผลิต 1', 'ฝ่ายซัพพลายเชน', 'ส่วนงานวิศวกรรมโรงงาน', 'โรงงานระยอง', 'ธุรกิจซิเมนต์', 'บริษัท เอสซีจี แพคเกจจิ้ง จำกัด (มหาชน)', 'Saraburi', 'กิตติ สุวรรณ', 'mgr_1@company.com', 'user25@company.com'),
    ('usr026', 'Password123', 'อรทัย รุ่งเรือง', 'อรทัย', 'รุ่งเรือง', 'วิศวกรซ่อมบำรุง', 'หน่วยผลิต 1', 'ฝ่ายความปลอดภัยและสิ่งแวดล้อม', 'ส่วนงานวิศวกรรมโรงงาน', 'โรงงานสระบุรี', 'ธุรกิจซิเมนต์', 'บริษัท เอสซีจี รูฟฟิ่ง จำกัด', 'Rayong', 'ประยุทธ์ มั่นคง', 'mgr_1@company.com', 'user26@company.com'),
    ('usr027', 'Password123', 'จันทิมา แสงทอง', 'จันทิมา', 'แสงทอง', 'วิศวกรซ่อมบำรุง', 'หน่วยผลิต 1', 'ฝ่ายซ่อมบำรุง', 'ส่วนงานวิศวกรรมโรงงาน', 'โรงงานบางซื่อ', 'ธุรกิจซิเมนต์', 'บริษัท เอสซีจี ซิเมนต์ จำกัด', 'Bangkok', 'อารีย์ ไดเรกเตอร์', 'mgr_1@company.com', 'user27@company.com'),
    ('usr028', 'Password123', 'วิไลพร สุวรรณ', 'วิไลพร', 'สุวรรณ', 'วิศวกรเครื่องกล', 'หน่วยซ่อมไฟฟ้า', 'ฝ่ายซัพพลายเชน', 'ส่วนงานสนับสนุน', 'โรงงานระยอง', 'ธุรกิจผลิตภัณฑ์ก่อสร้าง', 'บริษัท เอสซีจี ซิเมนต์ จำกัด', 'Rayong', 'วิชัย ผู้จัดการ', 'mgr_4@company.com', 'user28@company.com'),
    ('usr029', 'Password123', 'ศิริพรรณ เจริญชัย', 'ศิริพรรณ', 'เจริญชัย', 'ช่างซ่อมไฟฟ้า', 'หน่วยซ่อมไฟฟ้า', 'ฝ่ายผลิต', 'ส่วนงานวิศวกรรมโรงงาน', 'โรงงานสระบุรี', 'ธุรกิจผลิตภัณฑ์ก่อสร้าง', 'บริษัท เอสซีจี แพคเกจจิ้ง จำกัด (มหาชน)', 'Bangkok', 'กิตติ สุวรรณ', 'mgr_1@company.com', 'user29@company.com'),
    ('usr030', 'Password123', 'อุมาพร ชัยยะ', 'อุมาพร', 'ชัยยะ', 'เจ้าหน้าที่ความปลอดภัย', 'หน่วยซ่อมเครื่องกล', 'ฝ่ายความปลอดภัยและสิ่งแวดล้อม', 'ส่วนงานสนับสนุน', 'โรงงานบางซื่อ', 'ธุรกิจซิเมนต์', 'บริษัท เอสซีจี รูฟฟิ่ง จำกัด', 'Bangkok', 'วิชัย ผู้จัดการ', 'mgr_5@company.com', 'user30@company.com');